import pyautogui as pg, time as tm
os = input("Windows or Linux[w/l] >> ")
if os == "w":
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
    os.system('start https://digital.censo.gob.ar/#/app/app-codigo')
elif os == "l":
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
    os.system('xdg-open "https://digital.censo.gob.ar/#/app/app-codigo"')
else:
    print("[-] Sistema operativo no procesado...")

while True:
    pg.press('f5')
    pg.hotkey('ctrl','tab')
